trigger: none

pr:
- master

pool: 
  name: 1ES-hosted-pool-scrub1

jobs:
- job: queue_azdo
  timeoutInMinutes: 360
  steps:
  - bash: |
      echo $(System.PullRequest.PullRequestNumber)
    displayName: Print PR Num

  - task: Bash@3
    inputs:
      targetType: 'filePath'
      filePath: './azure-pipelines/queue_ado.sh'
      failOnStderr: true
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      PR_NUM: $(System.PullRequest.PullRequestNumber)
    displayName: Queue Validation Build and Monitor Status
