#!/bin/bash
set -e

mkdir -p /etc/udev/rules.d
cat <<'EOF' > /etc/udev/rules.d/60-rdma-persistent-naming.rules
# Suppressing/overwriting the udev rule from rdma_core package.

ACTION!="add", GOTO="azure_rdma_end"
SUBSYSTEM!="infiniband", GOTO="azure_rdma_end"

# Override the vendor policy; keep kernel names outside the Azure IB mapping.
PROGRAM="rdma_rename %k NAME_KERNEL"

# VMBus and PCI attributes belong to different ancestors, so match them separately.
SUBSYSTEMS=="vmbus", ATTRS{class_id}=="{44c4f61d-4444-4400-9d52-802e27ede19f}", ENV{.AZURE_VPCI}="1"
ENV{.AZURE_VPCI}!="1", GOTO="azure_rdma_end"
ATTR{ports/1/link_layer}!="InfiniBand", GOTO="azure_rdma_end"

# Azure exposes the ordered IB NIC index in the guest PCI domain.
SUBSYSTEMS=="pci", ATTRS{vendor}=="0x15b3", KERNELS=="0101:00:00.0", PROGRAM="rdma_rename %k NAME_FIXED mlx5_ib0"
SUBSYSTEMS=="pci", ATTRS{vendor}=="0x15b3", KERNELS=="0102:00:00.0", PROGRAM="rdma_rename %k NAME_FIXED mlx5_ib1"
SUBSYSTEMS=="pci", ATTRS{vendor}=="0x15b3", KERNELS=="0103:00:00.0", PROGRAM="rdma_rename %k NAME_FIXED mlx5_ib2"
SUBSYSTEMS=="pci", ATTRS{vendor}=="0x15b3", KERNELS=="0104:00:00.0", PROGRAM="rdma_rename %k NAME_FIXED mlx5_ib3"
SUBSYSTEMS=="pci", ATTRS{vendor}=="0x15b3", KERNELS=="0105:00:00.0", PROGRAM="rdma_rename %k NAME_FIXED mlx5_ib4"
SUBSYSTEMS=="pci", ATTRS{vendor}=="0x15b3", KERNELS=="0106:00:00.0", PROGRAM="rdma_rename %k NAME_FIXED mlx5_ib5"
SUBSYSTEMS=="pci", ATTRS{vendor}=="0x15b3", KERNELS=="0107:00:00.0", PROGRAM="rdma_rename %k NAME_FIXED mlx5_ib6"
SUBSYSTEMS=="pci", ATTRS{vendor}=="0x15b3", KERNELS=="0108:00:00.0", PROGRAM="rdma_rename %k NAME_FIXED mlx5_ib7"

LABEL="azure_rdma_end"
EOF

cat <<'EOF' > /etc/udev/rules.d/70-azure-accelnet-no-rdma.rules
# Azure FE Ethernet VFs expose verbs without usable RoCE. Keep Ethernet enabled.
# Match PCI bind, not child events generated by driver_reinit, to avoid a reload loop.
ACTION=="bind", SUBSYSTEM=="pci", DRIVER=="mlx5_core", \
  ATTR{vendor}=="0x15b3", ATTR{class}=="0x020000", \
  KERNEL=="????:00:02.0", \
  SUBSYSTEMS=="vmbus", ATTRS{class_id}=="{44c4f61d-4444-4400-9d52-802e27ede19f}", \
  RUN+="/bin/sh -c '/usr/sbin/devlink dev param set pci/%k name enable_rdma value false cmode driverinit && /usr/sbin/devlink dev reload pci/%k action driver_reinit'"
EOF

cat << EOF >> /etc/udev/rules.d/99-issm.rules
KERNEL=="issm*", NAME="infiniband/%k"
EOF

udevadm control --reload-rules
udevadm trigger
